[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ygroorn"
version = "0.1.0"
description = "You're Gonna Run Out Of Repo Names"
authors = [{name = "Gabriel Ong"}]
dependencies = ["typer", "numpy"]