name: Go CI

on:
  push:
    paths:
      - 'go/**'
  pull_request:
    paths:
      - 'go/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        run: |
          cd go
          go test ./pkg/...