name: Ruby CI

on:
  push:
    paths:
      - 'ruby/**'
  pull_request:
    paths:
      - 'ruby/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          cd ruby
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          cd ruby
          bundle exec rspec